scripts: Allow overriding the base
flatcar-linux/baselayout pull request #6
Opened 2020-09-30 18:10 UTC by krnowak

This PR is a part of systemd update.

When the second parameter is not provided, the script works as it used
to.

The reason for the change is to be able to run the script before
anything is provisioned in the new root filesystem. This will populate
the /etc/passwd and /etc/group files therein, so systemd-tmpfiles can
resolve the user and group information used in tmpfiles. This is a
change in systemd made in 246, as it only resolves the user and group
information from databases inside the overridden root filesystem (with
the --root flag).

This also extends the groups with the root and core groups to be
copied over, because these groups are needed by systemd-tmpfiles too.

Test build is here: 

# [Title: describe the change in one sentence]

[ describe the change in 1 - 3 paragraphs ]

# How to use

[ describe what reviewers need to do in order to validate this PR ]

# Testing done

[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]

2020-10-01 10:38 UTC, pothos approved these changes
Thanks, looks good in general. The `cl.ignition.v*.*root` tests seem to be broken by another cause.

2020-10-01 10:46 UTC, pothos requested changes
Ah, one moment, I though this is only for the dracut update but all were tested together so I don't know if the cause is here: `initrd-setup-root.service` failed and there is `systemd-tmpfiles[633]: baselayout-home.conf:3: Failed to resolve user 'core': No such process`.

2020-10-05 11:48 UTC, krnowak commented
This is fixed in bootengine.

2020-10-06 15:36 UTC, dongsupark approved these changes
Looks good, if CI passed.

2020-10-08 16:38 UTC, merged